// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: t.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Signature struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{0}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Tx struct {
	Data                 []byte     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	To                   string     `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Contract             string     `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	Op                   string     `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`
	Height               int64      `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Nonce                int64      `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Sig                  *Signature `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{1}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Tx) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Tx) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Tx) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *Tx) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Tx) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Tx) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Header struct {
	ParentHash           []byte   `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32    `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	TxsHash              []byte   `protobuf:"bytes,4,opt,name=txs_hash,json=txsHash,proto3" json:"txs_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{2}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *Header) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Header) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Header) GetTxsHash() []byte {
	if m != nil {
		return m.TxsHash
	}
	return nil
}

type Block struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Txs                  []*Tx    `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{3}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type NewBlock struct {
	Header               *Header    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Tx0                  *Tx        `protobuf:"bytes,2,opt,name=tx0,proto3" json:"tx0,omitempty"`
	FailedHashs          [][]byte   `protobuf:"bytes,3,rep,name=failed_hashs,json=failedHashs,proto3" json:"failed_hashs,omitempty"`
	Sig                  *Signature `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NewBlock) Reset()         { *m = NewBlock{} }
func (m *NewBlock) String() string { return proto.CompactTextString(m) }
func (*NewBlock) ProtoMessage()    {}
func (*NewBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{4}
}
func (m *NewBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBlock.Unmarshal(m, b)
}
func (m *NewBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBlock.Marshal(b, m, deterministic)
}
func (m *NewBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBlock.Merge(m, src)
}
func (m *NewBlock) XXX_Size() int {
	return xxx_messageInfo_NewBlock.Size(m)
}
func (m *NewBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBlock.DiscardUnknown(m)
}

var xxx_messageInfo_NewBlock proto.InternalMessageInfo

func (m *NewBlock) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *NewBlock) GetTx0() *Tx {
	if m != nil {
		return m.Tx0
	}
	return nil
}

func (m *NewBlock) GetFailedHashs() [][]byte {
	if m != nil {
		return m.FailedHashs
	}
	return nil
}

func (m *NewBlock) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type StoreBlock struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TxHashs              [][]byte `protobuf:"bytes,2,rep,name=tx_hashs,json=txHashs,proto3" json:"tx_hashs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreBlock) Reset()         { *m = StoreBlock{} }
func (m *StoreBlock) String() string { return proto.CompactTextString(m) }
func (*StoreBlock) ProtoMessage()    {}
func (*StoreBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{5}
}
func (m *StoreBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreBlock.Unmarshal(m, b)
}
func (m *StoreBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreBlock.Marshal(b, m, deterministic)
}
func (m *StoreBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreBlock.Merge(m, src)
}
func (m *StoreBlock) XXX_Size() int {
	return xxx_messageInfo_StoreBlock.Size(m)
}
func (m *StoreBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreBlock.DiscardUnknown(m)
}

var xxx_messageInfo_StoreBlock proto.InternalMessageInfo

func (m *StoreBlock) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *StoreBlock) GetTxHashs() [][]byte {
	if m != nil {
		return m.TxHashs
	}
	return nil
}

type VrfInput struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Seed                 []byte   `protobuf:"bytes,3,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VrfInput) Reset()         { *m = VrfInput{} }
func (m *VrfInput) String() string { return proto.CompactTextString(m) }
func (*VrfInput) ProtoMessage()    {}
func (*VrfInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{6}
}
func (m *VrfInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VrfInput.Unmarshal(m, b)
}
func (m *VrfInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VrfInput.Marshal(b, m, deterministic)
}
func (m *VrfInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VrfInput.Merge(m, src)
}
func (m *VrfInput) XXX_Size() int {
	return xxx_messageInfo_VrfInput.Size(m)
}
func (m *VrfInput) XXX_DiscardUnknown() {
	xxx_messageInfo_VrfInput.DiscardUnknown(m)
}

var xxx_messageInfo_VrfInput proto.InternalMessageInfo

func (m *VrfInput) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VrfInput) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *VrfInput) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

type VrfProof struct {
	Input                *VrfInput `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Proof                []byte    `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	Hash                 []byte    `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	PublicKey            []byte    `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VrfProof) Reset()         { *m = VrfProof{} }
func (m *VrfProof) String() string { return proto.CompactTextString(m) }
func (*VrfProof) ProtoMessage()    {}
func (*VrfProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{7}
}
func (m *VrfProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VrfProof.Unmarshal(m, b)
}
func (m *VrfProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VrfProof.Marshal(b, m, deterministic)
}
func (m *VrfProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VrfProof.Merge(m, src)
}
func (m *VrfProof) XXX_Size() int {
	return xxx_messageInfo_VrfProof.Size(m)
}
func (m *VrfProof) XXX_DiscardUnknown() {
	xxx_messageInfo_VrfProof.DiscardUnknown(m)
}

var xxx_messageInfo_VrfProof proto.InternalMessageInfo

func (m *VrfProof) GetInput() *VrfInput {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *VrfProof) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *VrfProof) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *VrfProof) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type SortHash struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Group                int32    `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SortHash) Reset()         { *m = SortHash{} }
func (m *SortHash) String() string { return proto.CompactTextString(m) }
func (*SortHash) ProtoMessage()    {}
func (*SortHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{8}
}
func (m *SortHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortHash.Unmarshal(m, b)
}
func (m *SortHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortHash.Marshal(b, m, deterministic)
}
func (m *SortHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortHash.Merge(m, src)
}
func (m *SortHash) XXX_Size() int {
	return xxx_messageInfo_SortHash.Size(m)
}
func (m *SortHash) XXX_DiscardUnknown() {
	xxx_messageInfo_SortHash.DiscardUnknown(m)
}

var xxx_messageInfo_SortHash proto.InternalMessageInfo

func (m *SortHash) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SortHash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SortHash) GetGroup() int32 {
	if m != nil {
		return m.Group
	}
	return 0
}

type Sortition struct {
	Hashs                []*SortHash `protobuf:"bytes,1,rep,name=hashs,proto3" json:"hashs,omitempty"`
	Proof                *VrfProof   `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	Sig                  *Signature  `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Sortition) Reset()         { *m = Sortition{} }
func (m *Sortition) String() string { return proto.CompactTextString(m) }
func (*Sortition) ProtoMessage()    {}
func (*Sortition) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{9}
}
func (m *Sortition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sortition.Unmarshal(m, b)
}
func (m *Sortition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sortition.Marshal(b, m, deterministic)
}
func (m *Sortition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sortition.Merge(m, src)
}
func (m *Sortition) XXX_Size() int {
	return xxx_messageInfo_Sortition.Size(m)
}
func (m *Sortition) XXX_DiscardUnknown() {
	xxx_messageInfo_Sortition.DiscardUnknown(m)
}

var xxx_messageInfo_Sortition proto.InternalMessageInfo

func (m *Sortition) GetHashs() []*SortHash {
	if m != nil {
		return m.Hashs
	}
	return nil
}

func (m *Sortition) GetProof() *VrfProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *Sortition) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type CommitteeVote struct {
	Height               int64      `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32      `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	CommHashs            [][]byte   `protobuf:"bytes,3,rep,name=comm_hashs,json=commHashs,proto3" json:"comm_hashs,omitempty"`
	MyHashs              [][]byte   `protobuf:"bytes,4,rep,name=my_hashs,json=myHashs,proto3" json:"my_hashs,omitempty"`
	Sig                  *Signature `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommitteeVote) Reset()         { *m = CommitteeVote{} }
func (m *CommitteeVote) String() string { return proto.CompactTextString(m) }
func (*CommitteeVote) ProtoMessage()    {}
func (*CommitteeVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{10}
}
func (m *CommitteeVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitteeVote.Unmarshal(m, b)
}
func (m *CommitteeVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitteeVote.Marshal(b, m, deterministic)
}
func (m *CommitteeVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitteeVote.Merge(m, src)
}
func (m *CommitteeVote) XXX_Size() int {
	return xxx_messageInfo_CommitteeVote.Size(m)
}
func (m *CommitteeVote) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitteeVote.DiscardUnknown(m)
}

var xxx_messageInfo_CommitteeVote proto.InternalMessageInfo

func (m *CommitteeVote) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *CommitteeVote) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *CommitteeVote) GetCommHashs() [][]byte {
	if m != nil {
		return m.CommHashs
	}
	return nil
}

func (m *CommitteeVote) GetMyHashs() [][]byte {
	if m != nil {
		return m.MyHashs
	}
	return nil
}

func (m *CommitteeVote) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type Vote struct {
	Height  int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round   int32    `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Hash    []byte   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	MyHashs [][]byte `protobuf:"bytes,4,rep,name=my_hashs,json=myHashs,proto3" json:"my_hashs,omitempty"`
	//   repeated SortHash sort_hashs = 4;
	Sig                  *Signature `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{11}
}
func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Vote) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Vote) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Vote) GetMyHashs() [][]byte {
	if m != nil {
		return m.MyHashs
	}
	return nil
}

func (m *Vote) GetSig() *Signature {
	if m != nil {
		return m.Sig
	}
	return nil
}

type StateSnapshot struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateSnapshot) Reset()         { *m = StateSnapshot{} }
func (m *StateSnapshot) String() string { return proto.CompactTextString(m) }
func (*StateSnapshot) ProtoMessage()    {}
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{12}
}
func (m *StateSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateSnapshot.Unmarshal(m, b)
}
func (m *StateSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateSnapshot.Marshal(b, m, deterministic)
}
func (m *StateSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateSnapshot.Merge(m, src)
}
func (m *StateSnapshot) XXX_Size() int {
	return xxx_messageInfo_StateSnapshot.Size(m)
}
func (m *StateSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_StateSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_StateSnapshot proto.InternalMessageInfo

type GetBlocks struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlocks) Reset()         { *m = GetBlocks{} }
func (m *GetBlocks) String() string { return proto.CompactTextString(m) }
func (*GetBlocks) ProtoMessage()    {}
func (*GetBlocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{13}
}
func (m *GetBlocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlocks.Unmarshal(m, b)
}
func (m *GetBlocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlocks.Marshal(b, m, deterministic)
}
func (m *GetBlocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlocks.Merge(m, src)
}
func (m *GetBlocks) XXX_Size() int {
	return xxx_messageInfo_GetBlocks.Size(m)
}
func (m *GetBlocks) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlocks.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlocks proto.InternalMessageInfo

func (m *GetBlocks) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetBlocks) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type BlocksReply struct {
	Bs                   []*Block `protobuf:"bytes,1,rep,name=bs,proto3" json:"bs,omitempty"`
	LastHeight           int64    `protobuf:"varint,2,opt,name=last_height,json=lastHeight,proto3" json:"last_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlocksReply) Reset()         { *m = BlocksReply{} }
func (m *BlocksReply) String() string { return proto.CompactTextString(m) }
func (*BlocksReply) ProtoMessage()    {}
func (*BlocksReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{14}
}
func (m *BlocksReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlocksReply.Unmarshal(m, b)
}
func (m *BlocksReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlocksReply.Marshal(b, m, deterministic)
}
func (m *BlocksReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlocksReply.Merge(m, src)
}
func (m *BlocksReply) XXX_Size() int {
	return xxx_messageInfo_BlocksReply.Size(m)
}
func (m *BlocksReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BlocksReply.DiscardUnknown(m)
}

var xxx_messageInfo_BlocksReply proto.InternalMessageInfo

func (m *BlocksReply) GetBs() []*Block {
	if m != nil {
		return m.Bs
	}
	return nil
}

func (m *BlocksReply) GetLastHeight() int64 {
	if m != nil {
		return m.LastHeight
	}
	return 0
}

type Msg struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{15}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Msg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PeerInfo struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ChainID              string   `protobuf:"bytes,7,opt,name=chainID,proto3" json:"chainID,omitempty"`
	Node                 string   `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Synced               bool     `protobuf:"varint,5,opt,name=synced,proto3" json:"synced,omitempty"`
	Header               *Header  `protobuf:"bytes,6,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{16}
}
func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfo.Unmarshal(m, b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
}
func (m *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(m, src)
}
func (m *PeerInfo) XXX_Size() int {
	return xxx_messageInfo_PeerInfo.Size(m)
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *PeerInfo) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *PeerInfo) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *PeerInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PeerInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PeerInfo) GetSynced() bool {
	if m != nil {
		return m.Synced
	}
	return false
}

func (m *PeerInfo) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type Amount struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Amount) Reset()         { *m = Amount{} }
func (m *Amount) String() string { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()    {}
func (*Amount) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{17}
}
func (m *Amount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Amount.Unmarshal(m, b)
}
func (m *Amount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Amount.Marshal(b, m, deterministic)
}
func (m *Amount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amount.Merge(m, src)
}
func (m *Amount) XXX_Size() int {
	return xxx_messageInfo_Amount.Size(m)
}
func (m *Amount) XXX_DiscardUnknown() {
	xxx_messageInfo_Amount.DiscardUnknown(m)
}

var xxx_messageInfo_Amount proto.InternalMessageInfo

func (m *Amount) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

type Ycc_Mine struct {
	Votes                []*Vote    `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes,omitempty"`
	Sort                 *Sortition `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Ycc_Mine) Reset()         { *m = Ycc_Mine{} }
func (m *Ycc_Mine) String() string { return proto.CompactTextString(m) }
func (*Ycc_Mine) ProtoMessage()    {}
func (*Ycc_Mine) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab95a3f7bbc9aa38, []int{18}
}
func (m *Ycc_Mine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ycc_Mine.Unmarshal(m, b)
}
func (m *Ycc_Mine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ycc_Mine.Marshal(b, m, deterministic)
}
func (m *Ycc_Mine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ycc_Mine.Merge(m, src)
}
func (m *Ycc_Mine) XXX_Size() int {
	return xxx_messageInfo_Ycc_Mine.Size(m)
}
func (m *Ycc_Mine) XXX_DiscardUnknown() {
	xxx_messageInfo_Ycc_Mine.DiscardUnknown(m)
}

var xxx_messageInfo_Ycc_Mine proto.InternalMessageInfo

func (m *Ycc_Mine) GetVotes() []*Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *Ycc_Mine) GetSort() *Sortition {
	if m != nil {
		return m.Sort
	}
	return nil
}

func init() {
	proto.RegisterType((*Signature)(nil), "types.Signature")
	proto.RegisterType((*Tx)(nil), "types.Tx")
	proto.RegisterType((*Header)(nil), "types.Header")
	proto.RegisterType((*Block)(nil), "types.Block")
	proto.RegisterType((*NewBlock)(nil), "types.NewBlock")
	proto.RegisterType((*StoreBlock)(nil), "types.StoreBlock")
	proto.RegisterType((*VrfInput)(nil), "types.VrfInput")
	proto.RegisterType((*VrfProof)(nil), "types.VrfProof")
	proto.RegisterType((*SortHash)(nil), "types.SortHash")
	proto.RegisterType((*Sortition)(nil), "types.Sortition")
	proto.RegisterType((*CommitteeVote)(nil), "types.CommitteeVote")
	proto.RegisterType((*Vote)(nil), "types.Vote")
	proto.RegisterType((*StateSnapshot)(nil), "types.StateSnapshot")
	proto.RegisterType((*GetBlocks)(nil), "types.GetBlocks")
	proto.RegisterType((*BlocksReply)(nil), "types.BlocksReply")
	proto.RegisterType((*Msg)(nil), "types.Msg")
	proto.RegisterType((*PeerInfo)(nil), "types.PeerInfo")
	proto.RegisterType((*Amount)(nil), "types.Amount")
	proto.RegisterType((*Ycc_Mine)(nil), "types.Ycc_Mine")
}

func init() { proto.RegisterFile("t.proto", fileDescriptor_ab95a3f7bbc9aa38) }

var fileDescriptor_ab95a3f7bbc9aa38 = []byte{
	// 817 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6a, 0x23, 0x47,
	0x10, 0x66, 0xfe, 0xa4, 0x99, 0x92, 0x9c, 0x35, 0x8d, 0x59, 0x66, 0x93, 0x2c, 0xd1, 0x36, 0x59,
	0xd0, 0x49, 0xbb, 0x38, 0x87, 0x1c, 0x72, 0xca, 0x26, 0x10, 0x39, 0x6b, 0x1b, 0xd3, 0x32, 0x86,
	0xe4, 0x22, 0x5a, 0x33, 0x2d, 0x69, 0xb0, 0xd4, 0x3d, 0x74, 0xb7, 0x1c, 0x29, 0x90, 0x73, 0x9e,
	0x20, 0xa7, 0xdc, 0xf3, 0x16, 0x79, 0xb7, 0xd0, 0x3f, 0x23, 0x4b, 0xc2, 0x08, 0x9c, 0xbd, 0xf5,
	0x57, 0xd5, 0xf3, 0xd5, 0x57, 0x3f, 0x5d, 0x03, 0x6d, 0x3d, 0xa8, 0xa5, 0xd0, 0x02, 0x25, 0x7a,
	0x53, 0x33, 0x85, 0x87, 0x90, 0x8d, 0xaa, 0x19, 0xa7, 0x7a, 0x25, 0x19, 0x7a, 0x0d, 0x50, 0xaf,
	0x26, 0x8b, 0xaa, 0x18, 0xdf, 0xb3, 0x4d, 0x1e, 0xf4, 0x82, 0x7e, 0x97, 0x64, 0xce, 0xf2, 0x91,
	0x6d, 0xd0, 0x97, 0x3b, 0x77, 0xf3, 0xd0, 0x79, 0xb7, 0x06, 0xfc, 0x4f, 0x00, 0xe1, 0xed, 0x1a,
	0x21, 0x88, 0x4b, 0xaa, 0xa9, 0xff, 0xda, 0x9e, 0xd1, 0x67, 0x10, 0x6a, 0x61, 0xbf, 0xc8, 0x48,
	0xa8, 0x05, 0xfa, 0x1c, 0xd2, 0x42, 0x70, 0x2d, 0x69, 0xa1, 0xf3, 0xc8, 0x5a, 0xb7, 0xd8, 0xdc,
	0x15, 0x75, 0x1e, 0xbb, 0xbb, 0xa2, 0x46, 0x2f, 0xa1, 0x35, 0x67, 0xd5, 0x6c, 0xae, 0xf3, 0xa4,
	0x17, 0xf4, 0x23, 0xe2, 0x11, 0x3a, 0x83, 0x84, 0x0b, 0x5e, 0xb0, 0xbc, 0x65, 0xcd, 0x0e, 0x20,
	0x0c, 0x91, 0xaa, 0x66, 0x79, 0xbb, 0x17, 0xf4, 0x3b, 0xe7, 0xa7, 0x03, 0x9b, 0xe3, 0x60, 0xab,
	0x91, 0x18, 0x27, 0x96, 0xd0, 0x1a, 0x32, 0x5a, 0x32, 0x89, 0xbe, 0x82, 0x4e, 0x4d, 0x25, 0xe3,
	0x7a, 0x3c, 0xa7, 0x6a, 0xee, 0x25, 0x83, 0x33, 0x0d, 0xa9, 0x9a, 0xef, 0x04, 0x0f, 0x0f, 0x83,
	0x4b, 0xb1, 0xe2, 0xa5, 0x55, 0x9f, 0x10, 0x07, 0xd0, 0x2b, 0x48, 0xf5, 0x5a, 0x39, 0xae, 0xd8,
	0x72, 0xb5, 0xf5, 0x5a, 0x19, 0x22, 0xfc, 0x11, 0x92, 0x0f, 0x0b, 0x51, 0xdc, 0xa3, 0xb7, 0x86,
	0xd1, 0x04, 0xb7, 0xd1, 0x3a, 0xe7, 0x27, 0x5e, 0xa3, 0x53, 0x44, 0xbc, 0x13, 0x7d, 0x01, 0x91,
	0x5e, 0xab, 0x3c, 0xec, 0x45, 0xfd, 0xce, 0x79, 0xe6, 0xef, 0xdc, 0xae, 0x89, 0xb1, 0xe2, 0xbf,
	0x02, 0x48, 0xaf, 0xd9, 0x6f, 0xcf, 0x27, 0x7c, 0x6f, 0xd3, 0x38, 0x24, 0x7c, 0x8f, 0xde, 0x40,
	0x77, 0x4a, 0xab, 0x05, 0x2b, 0xad, 0x76, 0x95, 0x47, 0xbd, 0xa8, 0xdf, 0x25, 0x1d, 0x67, 0x33,
	0xfa, 0x55, 0x53, 0xd8, 0xf8, 0x58, 0x61, 0xaf, 0x01, 0x46, 0x5a, 0x48, 0xf6, 0x2c, 0x61, 0xb6,
	0x68, 0x3e, 0x6e, 0x68, 0xe3, 0xb6, 0xf5, 0xda, 0xc6, 0xc4, 0x97, 0x90, 0xde, 0xc9, 0xe9, 0x05,
	0xaf, 0x57, 0x7a, 0xa7, 0x13, 0xc1, 0xd3, 0x9d, 0x08, 0x77, 0x3b, 0x81, 0x20, 0x56, 0x8c, 0xb9,
	0xf6, 0x74, 0x89, 0x3d, 0xe3, 0xdf, 0x2d, 0xdb, 0x8d, 0x14, 0x62, 0x8a, 0xde, 0x42, 0x52, 0x19,
	0x5a, 0x2f, 0xed, 0x85, 0x97, 0xd6, 0x44, 0x23, 0xce, 0x6b, 0xc8, 0x6b, 0x73, 0xdf, 0x0f, 0xbb,
	0x03, 0x86, 0xdc, 0xb6, 0xd8, 0x93, 0x9b, 0xf3, 0xc1, 0xcb, 0x89, 0x0f, 0x5e, 0x0e, 0xfe, 0x19,
	0xd2, 0x91, 0x90, 0x6e, 0xa6, 0xce, 0x4c, 0xec, 0x92, 0xad, 0x7d, 0x22, 0x0e, 0x6c, 0x49, 0xc3,
	0x1d, 0xd2, 0x33, 0x48, 0x66, 0x52, 0xac, 0xea, 0x66, 0xca, 0x2c, 0xc0, 0x7f, 0x40, 0x66, 0xb8,
	0x2a, 0x5d, 0x09, 0x6e, 0x12, 0x71, 0xa5, 0x0b, 0xec, 0xa4, 0x34, 0x89, 0x34, 0xc1, 0x88, 0xf3,
	0x9a, 0x6b, 0x8f, 0x89, 0xec, 0xe5, 0x6b, 0xeb, 0xd1, 0x64, 0xe6, 0x9b, 0x1c, 0x1d, 0x6b, 0xf2,
	0xdf, 0x01, 0x9c, 0xfc, 0x20, 0x96, 0xcb, 0x4a, 0x6b, 0xc6, 0xee, 0x84, 0x66, 0xcf, 0x6c, 0xcd,
	0x6b, 0x80, 0x42, 0x2c, 0x97, 0x7b, 0x93, 0x96, 0x19, 0x8b, 0x9b, 0xb3, 0x57, 0x90, 0x2e, 0x37,
	0xde, 0x19, 0xbb, 0x71, 0x58, 0x6e, 0xf6, 0x46, 0x30, 0x39, 0xa6, 0xee, 0xcf, 0x00, 0xe2, 0xff,
	0x21, 0xea, 0xa9, 0x96, 0x7e, 0xa2, 0x92, 0x17, 0x70, 0x32, 0xd2, 0x54, 0xb3, 0x11, 0xa7, 0xb5,
	0x9a, 0x0b, 0x8d, 0xbf, 0x85, 0xec, 0x27, 0xa6, 0xed, 0xdb, 0x50, 0x46, 0x86, 0xd2, 0x54, 0x36,
	0xea, 0x1c, 0x30, 0xd6, 0x42, 0xac, 0x78, 0xb3, 0x6d, 0x1c, 0xc0, 0x97, 0xd0, 0x71, 0x5f, 0x11,
	0x56, 0x2f, 0xcc, 0x16, 0x0e, 0x27, 0x4d, 0xbf, 0xbb, 0x3e, 0xb6, 0xf5, 0x93, 0x70, 0xa2, 0xcc,
	0x4a, 0x5b, 0x50, 0xa5, 0xc7, 0x7b, 0x6b, 0x0b, 0x8c, 0x69, 0x68, 0x2d, 0xf8, 0x1d, 0x44, 0x57,
	0x6a, 0x66, 0x42, 0x69, 0x51, 0x57, 0x85, 0x15, 0x90, 0x11, 0x07, 0xb6, 0xcb, 0x3b, 0x7c, 0x5c,
	0xde, 0xf8, 0xdf, 0x00, 0xd2, 0x1b, 0xc6, 0xe4, 0x05, 0x9f, 0x0a, 0x74, 0x0a, 0x51, 0x5d, 0x95,
	0xfe, 0x23, 0x73, 0x44, 0x39, 0xb4, 0x8b, 0x39, 0xad, 0xf8, 0xc5, 0x8f, 0x76, 0xeb, 0x66, 0xa4,
	0x81, 0x86, 0x8c, 0x8b, 0x92, 0xf9, 0xbd, 0x6f, 0xcf, 0xe6, 0xf6, 0x03, 0x93, 0xaa, 0x12, 0xdc,
	0x2f, 0xfe, 0x06, 0x1a, 0x0f, 0x2d, 0x4b, 0xc9, 0x94, 0xf2, 0xcb, 0xbf, 0x81, 0xa6, 0x95, 0x6a,
	0xc3, 0x0b, 0x56, 0xda, 0x82, 0xa7, 0xc4, 0xa3, 0x9d, 0x05, 0xd3, 0x3a, 0xb2, 0x60, 0xf0, 0x4b,
	0x68, 0x7d, 0xbf, 0x34, 0x85, 0x44, 0x5d, 0x08, 0xa8, 0x2f, 0x78, 0x40, 0xf1, 0x08, 0xd2, 0x5f,
	0x8a, 0x62, 0x7c, 0x55, 0x71, 0x86, 0xde, 0x40, 0xf2, 0x20, 0x34, 0x6b, 0xca, 0xda, 0x69, 0xde,
	0x87, 0xd0, 0x8c, 0x38, 0x0f, 0xfa, 0x1a, 0x62, 0x25, 0xa4, 0xf6, 0x2f, 0xe8, 0x74, 0xe7, 0xa1,
	0xd9, 0x97, 0x48, 0xac, 0xf7, 0x03, 0xfc, 0x9a, 0x0e, 0xde, 0x7d, 0x67, 0x7d, 0x93, 0x96, 0xfd,
	0xd1, 0x7e, 0xf3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x09, 0x22, 0x77, 0x46, 0x73, 0x07, 0x00,
	0x00,
}
